nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= v2.10.0"
    catalog.cattle.io/display-name: Virtualization Manager
